spring.profiles.active=aws                                                                                                                                                                                               

bedrock.region=eu-west-1                                                                                                                                                                                                 
bedrock.model=anthropic.claude-3-haiku-20240307-v1:0                                                                                                                                                                     

app.security.token=${SECRET_TOKEN}