spring.application.name=product-search-assistant
app.security.token=my-secret-token-123

spring.profiles.active=local
ollama.base-url=http://localhost:11434
ollama.model=llama3.2

resilience4j.circuitbreaker.instances.llm.failure-rate-threshold=100
resilience4j.circuitbreaker.instances.llm.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.llm.sliding-window-size=3
resilience4j.circuitbreaker.instances.llm.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.llm.permitted-number-of-calls-in-half-open-state=1
